### PR TITLE
Look and Feel Cleanup for Collection Pages

### PR DESCRIPTION
**Pull request by mtribone**
Makes accessibility, layout adjustments to the collection search bar to bring it closer to the mockup without creating a new collection landing page. Wraps the collection search in a fieldset with a legend.

Updates the tests for heading hierarchy and adjusted content.

Adds classes and divs for the presentation of the collection title and the browse button and finding aid link

## Description

Another round of styling and functionality to get a little further towards the customization path with UI elements and the Collection pages.

Connected to #960 #997 

## Changes

* SCSS file for collection-related styles
* SCSS file for search-related styles
* Some adjustments for accessibility on the search form and components. Default Blacklight is a little noisey.
* Adds layout for collection landing page and search/browse page
* Groups title and buttons together for styles
* Collection image size (1200x500)

### CODE REVIEW

**Comment by mtribone** [comment]
Screen Shot 2019-06-20 at 8 28 58 AM

**Comment by mtribone** [comment]
Screen Shot 2019-06-20 at 8 41 05 AM

**Comment by mtribone** [comment]
Screen Shot 2019-06-20 at 8 47 41 AM

**Comment by mtribone** [comment]
Screen Shot 2019-06-20 at 8 47 56 AM

**Comment by rschenk** [comment]
I like it! I do think it'd be worth taking another iteration at "flexboxing" the title/buttons/image but I think what we've got is good

**Pull request merged**
